### ISSUE TITLE
why writing so many interface ?

### ISSUE THREAD

**Issue by navotera** [ajitsing/ExpenseManager#1]
i just reading this : 
[Do I need to use an interface when only one class will ever implement it?](http://programmers.stackexchange.com/questions/159813/do-i-need-to-use-an-interface-when-only-one-class-will-ever-implement-it)

sorry can u explain in your folder structure / design pattern why u create many interfaces ? thanks

**Comment by ajitsing** [comment]
All the interfaces that I have created are implemented by Activities or Fragments. The idea here is that all the Android specific code should be inside activity or fragment. When Presenter needs to execute some android code, it will execute it via an interface which is nothing but Activity or Fragment.

**Why not pass Activity/Fragment to Presenter instead of interface?**
If we pass an Activity or Fragment to presenter that means we are putting android code inside Presenter. Presenter is not meant to have android specific code. That is the first rule it will break.
Secondly, If we pass Activity to Presenter, Presenter will have a lot of power and it can do anything using that activity object e.g navigating to other Activity or starting a service etc.

To avoid all the android related stuff, we pass an interface to presenter, which gives the presenter a desired and limited functionality.

**Comment by navotera** [comment]
Thanks for your response, it took a while to understand what u mean by **Interface is just a bridge** in your explanation between activity and presenter as handling business logic.... but asking first then reading your code was worth. your answer seem a keyword before trying to decide what to find in your source code to understand MVP

between reading your answer and compare it to ur source code... i find that there is a library for MVP called mosby. i need your guide again can u elaborate what's the different with ur approach in mvp and mosby. thanks for your answer i appreciate it
